<?php

namespace App\Http\Controllers\Employee;

use App\Http\Controllers\Controller;
use App\Models\SupplyRequest;
use App\Models\RequestItem;
use App\Models\Supply;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class RequestController extends Controller
{
    // View all user's requests
    public function index()
    {
        $requests = SupplyRequest::where('user_id', auth()->id())
            ->with(['department', 'items.supply', 'managerApprover', 'adminReleaser'])
            ->latest()
            ->paginate(20);

        return view('employee.requests.index', compact('requests'));
    }

    // View single request
    public function show($id)
    {
        $request = SupplyRequest::where('user_id', auth()->id())
            ->with(['department', 'items.supply', 'managerApprover', 'adminReleaser'])
            ->findOrFail($id);

        return view('employee.requests.show', compact('request'));
    }

    // Submit standard request
public function store(Request $request)
{
    $validator = Validator::make($request->all(), [
        'purpose' => 'required|string|max:500',
        'budget_type' => 'required|in:budgeted,not_budgeted',
        'items' => 'required|array|min:1',
        'items.*.supply_id' => 'required|exists:supplies,id',
        'items.*.quantity' => 'required|integer|min:1',
    ]);

    if ($validator->fails()) {
        return response()->json([
            'success' => false,
            'errors' => $validator->errors()
        ], 422);
    }

    DB::beginTransaction();
    try {
        // Create the supply request (SR number auto-generated by boot method)
        $supplyRequest = SupplyRequest::create([
            'user_id' => auth()->id(),
            'department_id' => auth()->user()->department_id,
            'request_type' => 'standard',
            'budget_type' => $request->budget_type,
            'purpose' => $request->purpose,
            'status' => 'pending',
        ]);

        // Add items
        foreach ($request->items as $item) {
            $supply = Supply::find($item['supply_id']);
            
            $supplyRequest->items()->create([
                'supply_id' => $item['supply_id'],
                'item_code' => $supply->item_code,
                'item_name' => $supply->name,
                'quantity' => $item['quantity'],
            ]);
        }

        DB::commit();

        return response()->json([
            'success' => true,
            'message' => 'Request submitted successfully',
            'sr_number' => $supplyRequest->sr_number  // ADD THIS
        ]);
    } catch (\Exception $e) {
        DB::rollBack();
        return response()->json([
            'success' => false,
            'message' => 'Failed to submit request'
        ], 500);
    }
}

    // Submit special request (non-catalog item)
public function storeSpecial(Request $request)
{
    $validator = Validator::make($request->all(), [
        'budget_type' => 'required|in:budgeted,not_budgeted',
        'item_description' => 'required|string|max:1000',
        'purpose' => 'required|string|max:500',
    ]);

    if ($validator->fails()) {
        return response()->json([
            'success' => false,
            'errors' => $validator->errors()
        ], 422);
    }

    try {
        $supplyRequest = SupplyRequest::create([
            'user_id' => auth()->id(),
            'department_id' => auth()->user()->department_id,
            'request_type' => 'special',
            'budget_type' => $request->budget_type,
            'purpose' => $request->purpose,
            'special_item_description' => $request->item_description,
            'status' => 'pending',
        ]);

        return response()->json([
            'success' => true,
            'message' => 'Custom request submitted successfully',
            'sr_number' => $supplyRequest->sr_number
        ]);
    } catch (\Exception $e) {
        \Log::error('Special request error: ' . $e->getMessage());
        
        return response()->json([
            'success' => false,
            'message' => 'Failed to submit request: ' . $e->getMessage()
        ], 500);
    }
}

    // Cancel pending request
    public function cancel($id)
    {
        $supplyRequest = SupplyRequest::where('user_id', auth()->id())
            ->where('id', $id)
            ->where('status', 'pending')
            ->firstOrFail();

        $supplyRequest->delete();

        return response()->json([
            'success' => true,
            'message' => 'Request cancelled successfully.'
        ]);
    }
}